name: postgresql-cdc

services:
  postgresql:
    container_name: postgresql
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 5432:5432
    command: ["postgres", "-c", "wal_level=logical"]

  rabbitmq:
    container_name: queue
    image: rabbitmq:3.12.14-management
    ports:
      - 5672:5672
      - 15672:15672