name: postgresql-cdc

services:
  postgresqldb:
    container_name: postgresqldb
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 5432:5432
    command: ["postgres", "-c", "wal_level=logical"]
    volumes:
      - ./postgresql/init.sql://docker-entrypoint-initdb.d/init.sql

  mariadb:
    container_name: mariadb
    image: mariadb
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/init.sql://docker-entrypoint-initdb.d/init.sql
    

  rabbitmq:
    container_name: queue
    image: rabbitmq:3.12.14-management
    ports:
      - 5672:5672
      - 15672:15672