name: postgresql-cdc

services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=requests
    ports:
      - 5432:5432
    volumes:
      - psql_volume:/var/lib/postgresql/data
    command: ["postgres", "-c", "wal_level=logical"]

volumes:
  psql_volume: